=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/xs/KPI.xsd
<?xml version="1.0" encoding="UTF-8"?>
  <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="KPI">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="ID" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="ALIAS" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="COMMENT" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="TITEL" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="STAND" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="TYPE" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element ref="CALC" minOccurs="0"  maxOccurs="1"/>
          <xsd:element ref="RULES" minOccurs="0"  maxOccurs="1"/>
          <xsd:element ref="USED" minOccurs="0"  maxOccurs="1"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="CALC">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element ref="CHILD" minOccurs="0"  maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>
 
    <xsd:element name="CHILD">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="SIGN" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="ALIAS" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="LINK" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="RULES">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element ref="RULE" minOccurs="0"  maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="RULE">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element ref="PART" minOccurs="0"  maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="PART">
      <xsd:complexType>
	<xs:simpleContent>
	  <xs:extension base="xsd:String">
	    <xs:attribute name="type" type="xs:String" use="required"/>
	  </xs:extension>
	</xs:simpleContent>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="USED">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element ref="BY" minOccurs="0"  maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

    <xsd:element name="BY">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element name="ALIAS" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
          <xsd:element name="LINK" type="xsd:string" minOccurs="1"  maxOccurs="1"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:element>

  </xsd:schema>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/KPID009.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>KPID009</ID>
  <ALIAS>Risikokapital Gesamt</ALIAS>
  <COMMENT></COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Calculated</TYPE>
  <CALC>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Diversifikation über Erst- und Rückversicherung</ALIAS>
      <LINK>KPIR010</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Diversifikation über Segmente</ALIAS>
      <LINK>KPIR009</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Diversifikation über Gesellschaften</ALIAS>
      <LINK>KPIR008</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Diversifikation über Risikoarten</ALIAS>
      <LINK>KPID008</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Operationale Risiken</ALIAS>
      <LINK>RK04</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>VT</ALIAS>
      <LINK>RK03</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Kredit</ALIAS>
      <LINK>RK02</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Markt</ALIAS>
      <LINK>RK01</LINK>
    </CHILD>
  </CALC>
  <RULES>
  </RULES>
  <USED>
    <BY>
      <ALIAS>Risikokapital Gesamt Durchschnitt</ALIAS>
      <LINK>KPID009M</LINK>
    </BY>
    <BY>
      <ALIAS>Gebundenes überschüssiges Kapital</ALIAS>
      <LINK>KPID042</LINK>
    </BY>
    <BY>
      <ALIAS>Risikokapital Gruppensicht</ALIAS>
      <LINK>KPID010</LINK>
    </BY>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/MCEV01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>

<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  
  <ID>MCEV01</ID>
  
  <TITEL>Subsummierter Steuersatz</TITEL>
  
  <ALIAS>MCEV 1.1. GJ ohne Frictional CoC</ALIAS>
  
  <COMMENT>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.   Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.   Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.   Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.   Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis.   At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. </COMMENT>

  <TYPE>Input</TYPE>

  <STAND></STAND>



  <RULES>
    <RULE>
<PART type="normal"></PART>
<PART type="Link">KPIR006</PART>
<PART type="normal">
=IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,IF(SUBST(!EPR_Segmente,1,7)@='Segment',STET,IF(</PART>
<PART type="Link">EK03</PART>
<PART type="normal">
=0,</PART>
<PART type="Link">ECON201</PART>
<PART type="normal">
,</PART>
<PART type="Link">EK03</PART>
<PART type="normal">
)));</PART></RULE>
    
    
    
    <RULE><PART type="normal"></PART>
<PART type="Link">KPID069</PART>
<PART type="normal">
=IF(SUBST(!EPR_Segmente,1,7)@='Segment',STET,IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,</PART>
<PART type="Link">EK10</PART>
<PART type="normal">
-</PART>
<PART type="Link">EK03VJ</PART>
<PART type="normal">
+</PART>
<PART type="Link">KPIR006VJ</PART>
<PART type="normal">
));</PART></RULE>
    <RULE><PART type="normal"></PART>
<PART type="Link">KPID020</PART>
<PART type="normal">
=IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,</PART>
<PART type="Link">MCEV33</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPIR006</PART>
<PART type="normal">
);</PART></RULE> 
  <RULE><PART type="normal"></PART>
<PART type="Link">KPIR041</PART>
<PART type="normal">
=IF(SUBST(!EPR_Segmente,1,7)@='Segment',STET,IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,</PART>
<PART type="Link">MVM</PART>
<PART type="normal">
));</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">MCEV33</PART>
<PART type="normal">
=IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,</PART>
<PART type="Link">MCEV29</PART>
<PART type="normal">
+</PART>
<PART type="Link">KPIR041</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPID002</PART>
<PART type="normal">
=IF(</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
 =0,0,</PART>
<PART type="Link">MCEV33</PART>
<PART type="normal">
-</PART>
<PART type="Source">MCEV01</PART>
<PART type="normal">
);</PART></RULE>
  </RULES>
    <USED>
    <BY>
      <ALIAS>MCEV 31.12. GJ (vor Div.abfluss und Kapitalmaﬂnahmen)</ALIAS>
      <LINK>MCEV27</LINK>
    </BY>
    <BY>
      <ALIAS>Delta MCEV (ohne Abzug FricCoC)</ALIAS>
      <LINK>KPID002</LINK>
    </BY>
    <BY>
      <ALIAS>MCEV-Uplift 1.1.</ALIAS>
      <LINK>KPID020H</LINK>
    </BY>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/KPID009VJ.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>KPID009VJ</ID>
  <ALIAS>Risikokapital Gesamt 1.1.</ALIAS>
  <COMMENT></COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Vorjahreswert</TYPE>
  <RULES>
  </RULES>
  <USED>
    <BY>
      <ALIAS>Risikokapital Gesamt Durchschnitt</ALIAS>
      <LINK>KPID009M</LINK>
    </BY>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/KPID009M.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>KPID009M</ID>
  <ALIAS>Risikokapital Gesamt Durchschnitt</ALIAS>
  <COMMENT></COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Calculated</TYPE>
  <CALC>
    <CHILD>
      <SIGN>0,5*</SIGN>
      <ALIAS>Risikokapital Gesamt 1.1.</ALIAS>
      <LINK>KPID009VJ</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+0,5*</SIGN>
      <ALIAS>Risikokapital Gesamt</ALIAS>
      <LINK>KPID009</LINK>
    </CHILD>
  </CALC>
  <RULES>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR025</PART>
<PART type="normal">
=IF((</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPID014</PART>
<PART type="normal">
)=0,0,(</PART>
<PART type="Link">KPID027</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPIR019b</PART>
<PART type="normal">
)/(</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPID014</PART>
<PART type="normal">
));</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR026</PART>
<PART type="normal">
=IF((</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPID014</PART>
<PART type="normal">
)=0,0,(</PART>
<PART type="Link">EK07</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPIR019b</PART>
<PART type="normal">
)/(</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPID014</PART>
<PART type="normal">
));</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR027</PART>
<PART type="normal">
=(</PART>
<PART type="Link">KPID019aM</PART>
<PART type="normal">
+</PART>
<PART type="Link">KPID019bM</PART>
<PART type="normal">
)/(</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
+</PART>
<PART type="Link">KPID041M</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR039</PART>
<PART type="normal">
=</PART>
<PART type="Link">KPID054</PART>
<PART type="normal">
/</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
;</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR040</PART>
<PART type="normal">
=</PART>
<PART type="Link">KPID065</PART>
<PART type="normal">
/</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
;</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPID038M</PART>
<PART type="normal">
=</PART>
<PART type="Link">CC00M</PART>
<PART type="normal">
-</PART>
<PART type="Source">KPID009M</PART>
<PART type="normal">
;</PART></RULE>
  </RULES>
  <USED>
    <BY>
      <ALIAS>Risikokapital Gruppensicht Durchschnitt</ALIAS>
      <LINK>KPID061</LINK>
    </BY>
    <BY>
      <ALIAS>Gebundenes überschüssiges Kapital Durchschnitt</ALIAS>
      <LINK>KPID038M</LINK>
    </BY>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/KPID061.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>KPID061</ID>
  <ALIAS>Risikokapital Gruppensicht Durchschnitt</ALIAS>
  <COMMENT>WRS-Kennzahl</COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Calculated</TYPE>
  <CALC>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Diversifikation über Erst- und Rückversicherung</ALIAS>
      <LINK>KPIR010</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Risikokapital Gesamt Durchschnitt</ALIAS>
      <LINK>KPID009M</LINK>
    </CHILD>
  </CALC>
  <RULES>
  </RULES>
  <USED>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/KPID038M.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>KPID038M</ID>
  <ALIAS>Gebundenes überschüssiges Kapital Durchschnitt</ALIAS>
  <COMMENT></COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Calculated</TYPE>
  <CALC>
    <CHILD>
      <SIGN>-</SIGN>
      <ALIAS>Risikokapital Gesamt Durchschnitt</ALIAS>
      <LINK>KPID009M</LINK>
    </CHILD>
    <CHILD>
      <SIGN>+</SIGN>
      <ALIAS>Betriebsnotwendiges Eigenkapital inkl. Tol. (SRMF) Durchschnitt</ALIAS>
      <LINK>CC00M</LINK>
    </CHILD>
  </CALC>
  <RULES>
<RULE><PART type="normal"></PART>
<PART type="Source">KPID038M</PART>
<PART type="normal">
=</PART>
<PART type="Link">CC00M</PART>
<PART type="normal">
-</PART>
<PART type="Link">KPID009M</PART>
<PART type="normal">
;</PART></RULE>
  </RULES>
  <USED>
  </USED>
</KPI>

=== KaiHufenbach/NAK-Homepage/Beispiel Homepage Kennzahlenkatalog/STSZ2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="xs\KPI.xsl" ?>
<KPI xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="/xs/KPI.xsd">
  <ID>STSZ2</ID>
  <ALIAS>subsumierter Steuersatz</ALIAS>
  <COMMENT>Ist kein STSZ angegeben, wird der Wert von ERGO-Ebene genommen.</COMMENT>
  <TITEL>IRM EPR Kennzahlkatalog</TITEL>
  <STAND>24.6.11</STAND>
  <TYPE>Input</TYPE>
  <RULES>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR014</PART>
<PART type="normal">
=</PART>
<PART type="Link">KPID015</PART>
<PART type="normal">
*(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR015</PART>
<PART type="normal">
=</PART>
<PART type="Link">Zi00</PART>
<PART type="normal">
*(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR023</PART>
<PART type="normal">
=IF(</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
=0,IF(SUBST(!EPR_Segmente,1,7)@='Segment',STET,(</PART>
<PART type="Link">KA21</PART>
<PART type="normal">
-</PART>
<PART type="Link">KA17</PART>
<PART type="normal">
)*(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
)),(</PART>
<PART type="Link">KA21</PART>
<PART type="normal">
-</PART>
<PART type="Link">KA17</PART>
<PART type="normal">
)*(1-</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
));</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR033</PART>
<PART type="normal">
=IF(</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
=0,IF(SUBST(!EPR_Segmente,1,7)@='Segment',STET,</PART>
<PART type="Link">PR01</PART>
<PART type="normal">
*(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
)),</PART>
<PART type="Link">PR01</PART>
<PART type="normal">
*(1-</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
));</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR037</PART>
<PART type="normal">
=</PART>
<PART type="Link">KPIR033D</PART>
<PART type="normal">
/(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Link">KPIR032</PART>
<PART type="normal">
=</PART>
<PART type="Link">KPID048</PART>
<PART type="normal">
*(1-</PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
);</PART></RULE>
<RULE><PART type="normal"></PART>
<PART type="Source">STSZ2</PART>
<PART type="normal">
=IF(</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
=0,</PART>
<PART type="Link">STSZ','Eingabe Segment ERGO</PART>
<PART type="normal">
,</PART>
<PART type="Link">STSZ</PART>
<PART type="normal">
);</PART></RULE>
  </RULES>
  <USED>
  </USED>
</KPI>
