=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/xsd/page.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="page">
    <xs:complexType>  
      <xs:sequence>
        <xs:element name="pageInfo" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="nr" type="xs:int" use="required" />
            <xs:attribute name="lastPage" type="xs:boolean" use="optional" default="false"/>
            <xs:attribute name="chapter" type="xs:string" use="required" />
            <xs:attribute name="typ" use="required">
                  <xs:simpleType>
                      <xs:restriction base="xs:string">
                          <xs:enumeration value="normal"/>
                          <xs:enumeration value="start"/>
                          <xs:enumeration value="quiz"/>
                          <xs:enumeration value="impressum"/>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:attribute>
          </xs:complexType>
        </xs:element>
          <xs:choice>
              <xs:group ref="normal"/>
              <xs:group ref="quiz"/>
          </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


    <xs:group name="quiz">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="quizOptions">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="2" maxOccurs="unbounded" name="rank">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element ref="picture" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                                <xs:attribute name="from" type="xs:int" use="required"/>
                                <xs:attribute name="to" type="xs:int" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="questions" type="xs:int" use="required" />
                </xs:complexType>
                
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="question">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="picture" minOccurs="0" maxOccurs="1"/>
                        <xs:element name="option" minOccurs="2" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="rightAnswer" type="xs:boolean" use="optional" default="false"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="question" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <xs:group name="normal">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="left">
                <xs:complexType>
                    <xs:group ref="normalPageContent"/>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="right">
                <xs:complexType>
                    <xs:group ref="normalPageContent"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    
    <xs:group name="normalPageContent">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="paragraph"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="picture"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <xs:element name ="paragraph">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="headline" type="xs:string" use="optional" />
                    <xs:attribute name="versalien" use="optional" default="false"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="picture">
        <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="file" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Start_1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="true" chapter="Start" typ="normal" />
    <left>
        <picture name="Strand und Palmen" file="bild1.png"/>
      <paragraph>
        Die Bahamas (englisch The Bahamas) sind ein Inselstaat  im Nordatlantik und Teil der Westindischen Inseln. Sie liegen südöstlich der USA sowie nordöstlich von Kuba und werden zu Mittelamerika gezählt. Von den mehr als 700 Bahamainseln sind nur 30 bewohnt. Die Inselgruppe erhielt ihren Namen durch die spanischen Eroberer. Sie nannten die Gewässer um die Inseln Baja Mar (spanisch für ‚flaches Meer‘), woraus später Bahamas wurde.
      </paragraph>
    </left>
    <right>
        <paragraph>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</paragraph>
        <picture name="Die Flagge der Bahamas" file="flagge.png" />
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Kultur_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="false" chapter="Kultur" typ="normal" />
    <left>
      <picture name="Holzschnitzereien" file="kultur_bild_1_klein.png"/>

      <paragraph headline="Geschichte">
        Mehr als 340'000 Menschen leben in den Bahamas. Mehr als 80% der Bahamesen leben hauptsächlich in städ- tischen Gebieten auf den Hauptinseln New Providence und Grand Bahama. Die Geschichte der Sklaverei in der Karibik ist verant- 
      </paragraph>

       </left>
    <right>
      <picture name="Ein dekorierter Baum" file="kultur_bild_2_klein.png" />

      <paragraph>
        wortlich, dass mehr als 85% der Bevölkerung eine schwarze Hautfarbe haben und 15% sind weißer Hautfarbe.

        Die Hauptsprache ist Englisch.
      </paragraph>
       </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Reiseziel_3.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="3" lastPage="true" chapter="Reiseziel" typ="normal" />
    <left>
        <picture name="Hotel Atlantic Bahamas" file="reiseziel_bild_5_klein.jpg"/>
        <paragraph headline="">
          Größe und Dienstleistungsangebot der Hotels sind sehr unterschiedlich. Luxushotels bieten Gepäck-, Pagen- und Zimmerservice, Sport- und Freizeitprogramm, Geschäfte und Swimmingpools; 
        </paragraph>
    </left>
    <right>
        <paragraph>einige haben Privatstrände und Golf- und Tennisplätze. Der Preis für Doppel- und Einzelzimmer ist oft derselbe. In den kleineren Hotels ist die Atmosphäre ungezwungener, es gibt weniger Freizeitanlagen, aber zumeist einen Speisesaal und eine Bar. Neuere Hotels wie das South Ocean Beach Resort auf der Insel New Providence bieten Sportanlagen und Zimmer mit höchstem Komfort. Im Crystal Palace am Cable Beach fehlt es nicht einmal an Kasino, Fitness-Center und Gourmet-Restaurant. In manchen Hotels ist der Bedienungsservice bereits im Preis inbegriffen.</paragraph>
        <picture name="Fischerboot" file="reiseziel_bild_6_klein.jpg" />
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Reiseziel_2.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="2" lastPage="false" chapter="Reiseziel" typ="normal" />
    <left>
       
        <paragraph headline="Klima">Die Bahamas weisen subtropisches Klima auf, da sie durch die Luftsysteme des Nordamerikanischen Kontinents abgekühlt werden. Im Sommer liegt die Durchschnittstemperatur bei ca. 28 °C, im Winter lässt der warme Golfstrom </paragraph>
      <picture name="Hafen" file="reiseziel_bild_3_klein.png"/>
    </left>
    <right>
      <picture name="Tempel" file="reiseziel_bild_4_klein.png" />
        <paragraph>  (Wassertemperaturen zwischen 24 und 29 °C) die Temperatur selten unter 20 °C sinken. Im Jahresmittel liegt die Temperatur bei 26 °C. Trotzdem können die Temperaturen im Winter gelegentlich bis auf unter 10 °C absinken.</paragraph>
     
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Kultur_2.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="2" lastPage="false" chapter="Kultur" typ="normal" />
    <left>
        <picture name="Junkanoo" file="kultur_bild_3_klein.png"/>
      <paragraph headline="Sprache">
        Es wird aber auch ein Gemisch von anderen karibischen Sprachen gesprochen, darunter vor allem Kreole unter den haitianischen Immigranten. Aber viele Bahamesen sprechen ihre eigene Art von Englisch, dass sich manchmal für den Fremden wie eine andere Sprache anhört. 
    </paragraph>
        </left>
    <right>
        <paragraph>
          Als Beispiel wird das "th" zum einem "t" und da "h" wird oft ausgelassen wie in "'appy birthday". "W" wird zum "v" und das "s" manchmal zum "z". Die grammatikalische Vergangenheits- und Zukunftsform wird oft ignoriert, da die Bahamesen sowieso nur in der Gegenwart leben. 

                  </paragraph>
        <picture name="Junkanoo Wagen" file="kultur_bild_4_klein.png" />
       
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Kultur_3.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="3" lastPage="true" chapter="Kultur" typ="normal" />
    <left>
           <paragraph headline="Musik">
             Die beliebteste Musik unter den Bahamesen ist die Junkanoo Musik. Junkanoo ist aber weit mehr als nur Musik. Erfahren Sie mehr über Junkanoo.

             Die bahamesische Musik beinhaltet auch andere karibische Rhythmen wie Calypso 

           </paragraph>
      <picture name="Junkanoo-Tänzer" file="kultur_bild_5_klein.png"/>
      <paragraph >
        sowie von Amerika inspirierte Rap und Hip Hop. Eine weiterer typischer bahamesischer 
      </paragraph>
    </left>

  <right>
        <paragraph>
          Musikstil ist der sogenannte Rake 'N' Scrape, welcher seinen Ursprung auf den Cat Islands hat. Diese Musik wird aber auch auf den anderen Inseln praktiziert. Normalerweise schlagen Rake 'N' Scrape Musiker die Goombay Trommel, kratzen an der Zimmermannssäge und spielen Melodien auf der Ziehharmonika.
          Die schönen Landschaften, die bunten Häuser und die Menschen auf den bahamesischen Inseln haben viele lokale Künstler inspiriert wie Amos Ferguson, Eddie Minnis, Brent Malone und andere. Kunstausstellung von lokalen Künstler werden in verschieden Kunstgalerien in Nassau ausgestellt. Empfehlenswerte Orte um gute lokale Kunst zu finden sind die Andrew Aitken Frame Art Gallery in Madeira St, Palmdale oder die Nassau Glass Company in Mackey St.

          Lokale Kunstausstellungen gibt es auch in der National Art Gallery of The Bahamas in West Hill St, Nassau.

        </paragraph>
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Reiseziel_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="false" chapter="Reiseziel" typ="normal" />
    <left>
        <picture name="Parlament" file="reiseziel_bild_1_klein.png"/>
        <paragraph headline="Tourismus">Haupterwerbszweig der Bahamas ist der Tourismus, in dem etwa 60 % der erwerbstätigen Bevölkerung beschäftigt sind. Die Infrastruktur für den Luft- und Seeverkehr ist gut ausgebaut, allerdings gibt es wegen der topographischen </paragraph>
    </left>
    <right>
        <paragraph>Bedingungen keine Eisenbahn. Brauchbare Landverkehrswege befinden sich auf New Providence, Grand Bahama und einigen anderen Inseln. Auf den Tourismus hat sich auch der Dreh mehrerer James-Bond-Filme auf den Bahamas günstig ausgewirkt. Die Bahamas beziehungsweise Nassau dienten unter anderem für Casino Royale, Feuerball und dessen 1983 erschienene Neuverfilmung "Sag niemals nie" als Drehorte.
        </paragraph>
        <picture name="Strand und Meer" file="reiseziel_bild_2_klein.png" />
    </right>
</page>
