=== KaiHufenbach/NAK-Homepage/Homepage/xml/xsd/page.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Kai -->
<!-- Beschreibung einer Seite. Eine "XML-Seite" stellt eine Buchseite dar.  -->
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="page">
    <xs:complexType>  
      <xs:sequence>
          <!-- Das pageInfo Element enthält Metadaten zu einer Seite und ordnet diese einem Kapitel zu -->
        <xs:element name="pageInfo" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="nr" type="xs:int" use="required" />
            <xs:attribute name="lastPage" type="xs:boolean" use="optional" default="false"/>
            <xs:attribute name="chapter" type="xs:string" use="required" />
            <xs:attribute name="typ" use="required">
                  <xs:simpleType>
                      <xs:restriction base="xs:string">
                          <xs:enumeration value="normal"/>
                          <xs:enumeration value="start"/>
                          <xs:enumeration value="quiz"/>
                          <xs:enumeration value="impressum"/>
                          <xs:enumeration value="overview"/>
                      </xs:restriction>
                  </xs:simpleType>
              </xs:attribute>
          </xs:complexType>
        </xs:element>
          <!-- Eine Seite kann nur eine der folgenden Gruppierungen enthalten: -->
          <xs:choice>
              <xs:group ref="normal"/>
              <xs:group ref="quiz"/>
              <xs:group ref="overview"/>
          </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


    <!-- Steckbriefgruppe -->
    <xs:group name="overview">
        <xs:sequence>
            <!-- Bildbereich oberhalb des Steckbriefes -->
            <xs:element ref="overviewPictureArea" minOccurs="1" maxOccurs="1"/>
            <!-- Eine Tabelle unten ist Pflicht -->
            <xs:element minOccurs="1" maxOccurs="1" ref="table"/>
        </xs:sequence>
    </xs:group>

    <!-- Beschreibung des oberen, "Bildteil" des Steckbriefes -->
    <xs:element name="overviewPictureArea">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="standardPicture" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="picture" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="hoverArea" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- Wenn eine Hover Area angegeben wird, muss ein Standard-Bild im Ziel bestimmt werden -->
                            <xs:element ref="picture" minOccurs="1" maxOccurs="1"/>
                            <xs:element ref="hoverPart" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <!-- Angabe des Hover Targets, hier wird sowohl das StandardPicture, als auch ggf. die DescriptionBox des Elements angezegit, auf dem der Hover vorliegt. -->
                        <xs:attribute name="targetx" type="xs:int" use="required"/>
                        <xs:attribute name="targety" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Schemadefinition eines Bereiches mit Hover-Eigenschaften -->
    <xs:element name="hoverPart">
        <xs:complexType>
            <xs:sequence>
                <!-- Muss ein Bild sein, über das man hovern kann -->
                <xs:element ref="picture" maxOccurs="1" minOccurs="1"/>
                <!-- Es kann an der Position des "targets" eine Description box erscheinen -->
                <xs:element name="descriptionBox" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <!-- Eine DescriptionBox kann normalen Seiteninhalt beinhalten -->
                        <xs:sequence>
                            <xs:group ref="normalPageContent"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <!-- Wo liegt der HoverPart, wie groß ist er? -->
            <!-- Diese Infos sind für die Fillerboxen Relevant -->
            <xs:attribute name="posx" type="xs:int" use="required"/>
            <xs:attribute name="posy" type="xs:int" use="required"/>
            <xs:attribute name="sizex" type="xs:int" use="required"/>
            <xs:attribute name="sizey" type="xs:int" use="required"/>
        </xs:complexType>
    </xs:element>
    
    <!-- Schemadefinition des Quizes -->
    <xs:group name="quiz">
        <xs:sequence>
            <!-- Beschreibung des Quiz -->
            <xs:element minOccurs="1" maxOccurs="1" name="quizOptions">
                <xs:complexType>
                    <xs:sequence>
                        <!-- Es können Ränge konfiguriert werden -->
                        <xs:element minOccurs="2" maxOccurs="unbounded" name="rank">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element ref="picture" maxOccurs="1" minOccurs="1"/>
                                </xs:sequence>
                                <xs:attribute name="from" type="xs:int" use="required"/>
                                <xs:attribute name="to" type="xs:int" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <!-- Maximale Anzahl von Fragen pro Quizu -->
                    <xs:attribute name="questions" type="xs:int" use="required" />
                </xs:complexType>
            </xs:element>
            <!-- Schemabeschreibung einer Frage: So wird ein Fragenkatalog angelegt -->
            <xs:element minOccurs="0" maxOccurs="unbounded" name="question">
                <xs:complexType>
                    <xs:sequence>
                        <!-- Der Frage kann ein Bild zugeordnet werden. -->
                        <xs:element ref="picture" minOccurs="0" maxOccurs="1"/>
                        <!-- Antwortmöglichkeiten der Frage, diese werden in zufälliger Reihenfolge dargestellt -->
                        <xs:element name="option" minOccurs="2" maxOccurs="3">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="rightAnswer" type="xs:boolean" use="optional" default="false"></xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <!-- Der eigentliche Fragentext -->
                    <xs:attribute name="question" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>

    <!-- Zusammenfassung eines zweispalten Layouts -->
    <xs:group name="normal">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="1" name="left">
                <xs:complexType>
                    <xs:group ref="normalPageContent"/>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" maxOccurs="1" name="right">
                <xs:complexType>
                    <xs:group ref="normalPageContent"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    
    <!-- Zusammenfassung des Seiteninhaltes -->
    <xs:group name="normalPageContent">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="paragraph"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="picture"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="table"/>
            </xs:choice>
        </xs:sequence>
    </xs:group>

    <!-- Allgemeines Tabellenelement -->
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <!-- Jede Spalte, sowie Zeile kann separat mit einer eigenen ID o. Klasse versehen werden. -->
                <!-- Diese so vergebenen Attribute haben die höchste Priorität -->
                <xs:element name="row" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="column" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:string" use="optional"/>
                                            <xs:attribute name="class" type="xs:string" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="optional"/>
                        <xs:attribute name="class" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="optional"/>
            <xs:attribute name="class" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>

    <!-- Allgemeines Textelement -->
    <xs:element name ="paragraph">
        <!-- Kann sowohl Text, als auch weitere Element (br) enthalten -->
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="br" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="headline" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>

    <!-- Allgemeines Bildelement -->
    <xs:element name="picture">
        <xs:complexType>
                    <xs:attribute name="name" type="xs:string" use="required" />
                    <xs:attribute name="file" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Steckbrief_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="true" chapter="Steckbrief" typ="overview" />
    <overviewPictureArea>
        <standardPicture>
            <picture file="steckbrief_karte.png" name="Inselgruppe der Bahamas"/>
        </standardPicture>
        <hoverArea targetx="330" targety="90">
            <picture file="steckbrief_hoverbild_start.png" name="Für weitere Informationen über die Inselgruppen mit der Maus streichen"/>
            <hoverPart posx="54" posy="91" sizex="116" sizey="85">
                <picture file="steckbrief_insel_obenlinks.png" name="hoverobenlinks"/>
                <descriptionBox>
                    <table>
                        <row>
                            <column>Grand Bahamas</column>
                        </row>
                        <row>
                            <column>Länge</column>
                            <column>154km</column>
                        </row>
                        <row>
                            <column>Breite</column>
                            <column>27km</column>
                        </row>
                        <row>
                            <column>Fläche</column>
                            <column>1373km²</column>
                        </row>
                        <row>
                            <column>Hauptort</column>
                            <column>Freeport</column>
                        </row>
                    </table>
                </descriptionBox>
            </hoverPart>
            <hoverPart posx="42" posy="162" sizex="67" sizey="104">
                <picture file="steckbrief_insel_untenlinks.png" name="hoveruntenlinks"/>
                <descriptionBox>
                    <table>
                        <row>
                            <column>Andros Island</column>
                        </row>
                        <row>
                            <column>Länge</column>
                            <column>167km</column>
                        </row>
                        <row>
                            <column>Breite</column>
                            <column>64km</column>
                        </row>
                        <row>
                            <column>Fläche</column>
                            <column>5957km²</column>
                        </row>
                        <row>
                            <column>Einwohner</column>
                            <column>7686</column>
                        </row>
                    </table>
                </descriptionBox>
            </hoverPart>
            <hoverPart posx="161" posy="163" sizex="123" sizey="96">
                <picture file="steckbrief_insel_untenrechts.png" name="hoveruntenrechts"/>
                <descriptionBox>
                    <table>
                        <row>
                            <column>Cat Island</column>
                        </row>
                        <row>
                            <column>Fläche</column>
                            <column>389km²</column>
                        </row>
                        <row>
                            <column>Einwohner</column>
                            <column>1700</column>
                        </row>
                        <row>
                            <column>Höchste Erhebung</column>
                            <column>63m</column>
                        </row>                   
                    </table>
                </descriptionBox>
            </hoverPart>
        </hoverArea>
    </overviewPictureArea>
    <table>
        <row>
            <column>
                Amtssprache
            </column>
            <column>
                Englisch
            </column>
        </row>
        <row>
            <column>
                Hauptstadt
            </column>
            <column>
                Nassau
            </column>
        </row>
        <row>
            <column>
                Staatsform
            </column>
            <column>
                Parlamentarische Monarchie
            </column>
        </row>
        <row>
            <column>
                Staatsoberhaupt
            </column>
            <column>
                Königin Elisabeth II.
            </column>
        </row>
        <row>
            <column>
                Regierungschef
            </column>
            <column>
                Premierminister Hubert Ingraham
            </column>
        </row>
        <row>
            <column>
                Fläche
            </column>
            <column>
                13.940 km²
            </column>
        </row>
        <row>
            <column>
                Einwohnerzahl
            </column>
            <column>
                309.156 (Quelle: CIA 2009)
            </column>
        </row>
        <row>
            <column>
                Bruttoinlandsprodukt
            </column>
            <column>
                19.781 US$ (34.)
            </column>
        </row>
        <row>
            <column>
                Nationalhymne
            </column>
            <column>
                March On, Bahamaland
            </column>
        </row>
    </table>
</page>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Reiseziel_2.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="2" lastPage="false" chapter="Reiseziel" typ="normal" />
    <left>
       
        <paragraph headline="Klima">Die Bahamas weisen sub- tropisches Klima auf, da sie durch die Luft- systeme des Nordameri- kanischen Kontinents runtergefreezed werden. Im Sommer liegt die Durchschnittstemperatur bei ca. 28 °C, im Win- ter lässt der warme Golfwind (Wassertempe- raturen zwischen </paragraph>
      <picture name="Hafen" file="reiseziel_bild_3_klein.png"/>
    </left>
    <right>
      <picture name="Tempel" file="reiseziel_bild_4_klein.png" />
        <paragraph>  24 und 29 °C) die Temperatur selten unter 0 °C sinken. Im Jahresmittel liegt die Temperatur bei 1 bis 50 °C. Trotzdem können die Tempe- raturen im Winter gelegentlich bis auf unter 10 °C absinken.</paragraph>
     
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Reiseziel_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="false" chapter="Reiseziel" typ="normal" />
    <left>
        <picture name="Parlament" file="reiseziel_bild_1_klein.png"/>
        <paragraph headline="Tourismus">Haupterwerbszweig der Bahamas ist der Tourismus, in dem etwa 60 % der erwerbstätigen Bevölkerung beschäftigt sind. Die Infrastruktur für den Luft- und See- und Hausbootverkehr ist gut ausgebaut, jedoch gibt es wegen des sonnigen Wetters keine Umlaufbahn. Brauchbare Landverkehrsrutschbahnen </paragraph>
    </left>
    <right>
        <paragraph>befinden sich auf New Providence, Grand Bahama und einigen anderen Inseln. Auf den Tourismus hat sich auch der Dreh mehrerer James-Bond-Filme auf den Bahamas günstig ausgewirkt. 
        </paragraph>
        <picture name="Strand und Meer" file="reiseziel_bild_2_klein.png" />
      <paragraph>
        Die Bahamas beziehungsweise Nassau dienten unter anderem für Casino Fatal, Episode II und dessen 1983 erschienene Neuverfilmung "Sag niemals Knie" als Drehorte.
      </paragraph>
    </right>
</page>

=== KaiHufenbach/NAK-Homepage/homepage/Projekt/xml/Steckbrief_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="true" chapter="Steckbrief" typ="overview" />
    <table>
        <row>
            <column>
                Amtssprache
            </column>
            <column>
                Englisch
            </column>
        </row>
        <row>
            <column>
                Hauptstadt
            </column>
            <column>
                Nassau
            </column>
        </row>
        <row>
            <column>
                Staatsform
            </column>
            <column>
                Parlamentarische Monarchie
            </column>
        </row>
        <row>
            <column>
                Staatsoberhaupt
            </column>
            <column>
                Königin Elisabeth II.
            </column>
        </row>
        <row>
            <column>
                Regierungschef
            </column>
            <column>
                Premierminister Hubert Ingraham
            </column>
        </row>
        <row>
            <column>
                Fläche
            </column>
            <column>
                13.940 km²
            </column>
        </row>
        <row>
            <column>
                Einwohnerzahl
            </column>
            <column>
                309.156 (Quelle: CIA 2009)
            </column>
        </row>
        <row>
            <column>
                Bruttoinlandsprodukt
            </column>
            <column>
                19.781 US$ (34.)
            </column>
        </row>
        <row>
            <column>
                Nationalhymne
            </column>
            <column>
                March On, Bahamaland
            </column>
        </row>
    </table>
</page>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Quiz_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="true" chapter="Quiz" typ="quiz" />
    <quizOptions questions="3">
        <rank from="0" to="1">
            <picture file="quiz_handtuchkrieger.png" name="Handtuchkrieger"/>
        </rank>
        <rank from="2" to="2">
            <picture file="quiz_tourist.png" name="Tourist"/>
        </rank>
        <rank from="3" to="3">
            <picture file="quiz_einheimischer.png" name="Einheimischer"/>
        </rank>
    </quizOptions>
    <question question="Was machen die da?">
        <picture name="Party" file="quiz_bild_2.png"/>
        <option rightAnswer="true">Junkanoo Karneval</option>
        <option >Ramalam Ding Dong</option>
        <option >Reeperbahn Festival</option>
    </question>

    <question question="Wie heißt dieses Hotel?">
        <picture name="Hotel" file="quiz_bild_3.png"/>
        <option >Hotel Atlantis Drama</option>
        <option rightAnswer="true">Hotel Atlantic Bahamas</option>
        <option >Hotel Alte Banane</option>
    </question>

    <question question="Warum gehören die Bahamas nicht zu Kuba?">
        <picture name="Fragezeichen" file="quiz_bild_uni.png"/>
        <option >Wegen Fidel</option>
        <option >Aus Bock</option>
        <option rightAnswer="true">Weil sie's können</option>
    </question>
  
  <question question="Was ist dein Lieblingsessen?">
    <picture name="Fragezeichen" file="quiz_bild_uni.png"/>
    <option rightAnswer="true">Bahama Bananas</option>
    <option >Pizza</option>
    <option >Döner</option>
  </question>

    <question question="Wo liegen die Bahamas?">
        <picture name="Fragezeichen" file="quiz_bild_uni.png"/>
        <option rightAnswer="true">In der Karibik</option>
        <option >Hinter Kuba</option>
        <option >Frag Mutti, die räumt doch immer auf</option>
    </question>

    <question question="Wer ist das Staatsoberhaupt der Bahamas?">
        <picture name="Karte" file="quiz_bild_1.png"/>
        <option rightAnswer="true">Die Queen</option>
        <option >Der Pabst</option>
        <option >Der Highlander.</option>
    </question>


</page>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Impressum_1.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="1" lastPage="true" chapter="Impressum" typ="normal" />
    <left>
      <paragraph headline="LLorem FH">

          gemäß § 5 TMG:<br></br>
          <br></br>
      Ipsumstraße 111<br></br>
      Hotel Alte Banane 77<br></br>
      90210 Gotham City<br></br>
          <br></br>
      Vertreten durch:
          <br></br>
      Herrn Kai Hufenbach<br></br>
      Herrn Oliver Plehn<br></br><br></br>
      </paragraph>
      <paragraph headline="Kontakt:">
          <br></br>
        Telefon:<br></br>
          +49 (0) 123 44 55 66<br></br>
          <br></br>
          Telefax:<br></br>
          +49 (0) 123 44 55 99<br></br>
          <br></br>
        E-Mail:<br></br>

        bahamas@pyjamas.de
      </paragraph>
    </left>
    <right>
      <paragraph headline="Umsatzsteuer-ID:">

      Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:<br></br>
      DE 999 999 999<br></br><br></br>
     
          Wirtschafts-Identifikationsnummer gemäß §139 c Abgabenordnung:<br></br>
      DE 999 999 999<br></br><br></br>
  </paragraph>
      <paragraph headline="Aufsichtsbehörde:">

      Landratsamt Oberquakenbrückszieglstadl<br></br><br></br>
      Quelle: Durch den vom Rechtsanwalt Sören Siebert bereitgestellten Impressum-Generator generiert.<br></br>
      </paragraph>
   

      </right>
</page>

=== KaiHufenbach/NAK-Homepage/Homepage/xml/Reiseziel_3.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="xslt/page.xslt" ?>
<page xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="./xsd/page.xsd">
    <pageInfo nr="3" lastPage="true" chapter="Reiseziel" typ="normal" />
    <left>
       <paragraph headline="Unterkunft">
         Größe und Dienstleis- tungsangebot der Hotels sind sehr unter- schiedlich. Luxushotels bieten Gepäck-, Pagen- und Zimmerservice, Sport- und Freizeit- programm, Geschäfte und Swimmingpools; einige haben Privatstrände und Golf- und Tennisplätze. Der Preis für Doppel- und Einzelzimmer ist oft derselbe.
       </paragraph>
      <picture name="Hotel Atlantic Bahamas" file="reiseziel_bild_5_klein.png"/>

    </left>
    <right>
      <paragraph>
        In den kleineren Hotels ist die Atmosphäre ungezwungener, es gibt weniger Freizeitanlagen, aber zumeist einen Speisesaal und eine Bar. Neuere Hotels wie das South Ocean Beach Resort auf der Insel New Providence bieten Sportanlagen und Zimmer mit höchstem Komfort.
      </paragraph>
          <picture name="Fischerboot" file="reiseziel_bild_6_klein.png" />
    </right>
</page>
